name: Deploy to VM Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy files to VM
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.HOST }} 
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_KEY }}
          source: '.' # 현재 디렉토리의 파일 및 폴더를 복사
          target: '/home/bot' # VM 인스턴스의 /home/bot 경로로 복사

      - name: SSH into VM and restart application
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }} 
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            port: 22
          script: |
            cd /home/bot
            node ./index.js